import yaml
from huggingface_hub import login
from smolagents import CodeAgent, InferenceClientModel, tool
# Try WebSearchTool first; fall back to DuckDuckGoSearchTool if needed
try:
    from smolagents import WebSearchTool
    SearchTool = WebSearchTool
except ImportError:
    from smolagents import DuckDuckGoSearchTool as SearchTool



CONFIG_FILE = "config.yaml"
query = (
    "What's the best value for money holiday caravan park, where I can book a site in NSW South Coast"
    "(between Nowra and Batemans Bay), that accepts dogs all year round and is located near a beach?"
)


   
def get_token_from_yaml():
    try:
        with open(CONFIG_FILE, "r") as f:
            cfg = yaml.safe_load(f)
            return cfg.get("HF_TOKEN") if isinstance(cfg, dict) else None
    except FileNotFoundError:
        print("Config file not found.")
        return None

@tool
def holiday_park_criteria(state: str, accepts_dogs: bool, near_beach: bool, budget: str, type: str, location: str) -> str:
    """
    Provides criteria for selecting holiday parks based on user preferences.
    Args:
        state: The state where the holiday park is located.
        accepts_dogs: Whether the park accepts dogs.
        near_beach: Whether the park is near the beach.
        budget: The budget for the holiday.
        type: The type of holiday park (e.g., caravan park, camping site).
        location: Specific location or region within the state.
    """
    
    type_map = {
        "site": "site",
        "camping": "site",
        "campsite": "site",
        "camping site": "site",
        "caravan": "site",
        "cabin": "cabin"
    }
    
    type_norm = type_map.get(type.lower(), None)
    if not type_norm:
        return "Error: Type must be 'caravan park', 'camping site', 'cabin', or 'holiday park'."
    criteria = f"State: {state}, Accepts Dogs: {accepts_dogs}, Near Beach: {near_beach}, Budget: {budget}, Type: {type_norm}, Location: {location}"
    return criteria

@tool
def prompt_builder(criteria: str) -> str:
    """
    Builds a query for the holiday park search based on user preferences.
    Args:
        criteria: The criteria string generated by holiday_park_criteria tool.
    """
    return f"Find holiday or caravan parks that meet the following criteria: {criteria}. Provide a summary of the top options with links to their websites."


def main():
    print("Welcome to the NSW Holiday Parks Review!")

    token = get_token_from_yaml()
    if token:
        login(token=token, add_to_git_credential=False)
        
    model_name = "deepseek-ai/DeepSeek-R1-Distill-Llama-70B"

    # Requires huggingface_hub >= 0.28.0 for provider=
    client = InferenceClientModel(model_id=model_name, provider="groq")
        
    # Include all tools: your custom tools + search tool instance
    tools = [holiday_park_criteria, prompt_builder, SearchTool()]
    
    # Optional: light instruction so the agent composes tools
    system_prompt = (
        "You can compose tools. If the user asks for holiday parks, first call "
        "holiday_park_criteria to build criteria, then query_builder to make a search string, "
        "then use the web search tool to find results. Summarize succinctly with sources."
    )

    agent = CodeAgent(model=client, tools=tools)
    response = agent.run(query)
    print(response)

if __name__ == "__main__":
    main()