"""Agent tools for holiday park search."""

from smolagents import tool
from constants import TYPE_MAP

def _clean_type(s: str) -> str:
    s = s.strip().lower()
    # collapse multiple spaces
    s = " ".join(s.split())
    return s

@tool
def holiday_park_criteria(
    state: str,
    accepts_dogs: bool,
    near_beach: bool,
    budget: str,
    type: str,
    location: str
) -> str:
    """
    Provides criteria for selecting holiday parks based on user preferences.
    
    Args:
        state: The state where the holiday park is located
        accepts_dogs: Whether the park accepts dogs
        near_beach: Whether the park is near the beach
        budget: The budget for the holiday
        type: The type of holiday park (e.g., caravan park, camping site, cabin)
        location: Specific location or region within the state
        
    Returns:
        Formatted criteria string
        
    Raises:
        ValueError: If type is not recognized
    """
    type_norm = TYPE_MAP.get(type.lower())
    
    t = _clean_type(type)
    type_norm = TYPE_MAP.get(t)
    if not type_norm:
        valid_types = ", ".join(sorted(set(TYPE_MAP.keys())))
        raise ValueError(f"Invalid type '{type}'. Must be one of: {valid_types}")
    
    criteria = (
        f"State: {state}, "
        f"Accepts Dogs: {accepts_dogs}, "
        f"Near Beach: {near_beach}, "
        f"Budget: {budget}, "
        f"Type: {type_norm}, "
        f"Location: {location}"
    )
    
    return criteria


@tool
def prompt_builder(criteria: str) -> str:
    """
    Builds a query for the holiday park search based on user preferences.
    
    Args:
        criteria: The criteria string generated by holiday_park_criteria tool
        
    Returns:
        Formatted search query
    """
    return (
        f"Find holiday or caravan parks that meet the following criteria: {criteria}. "
        f"Provide a summary of the top options with links to their websites."
    )